#!/usr/bin/env bash
# Hermetic backward-compat check: deployed 0.0.9 (origin/master = fbdfa17) vs current checkout.
# Builds the baseline in an isolated worktree, builds the current tree, extracts both
# contracts, and diffs them. Exits non-zero on any breaking change.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# The commit that produced the published 0.0.9. Override with BASELINE_REF=<ref> if needed.
BASELINE_REF="${BASELINE_REF:-fbdfa17}"

WORKDIR="$(mktemp -d -t cld-compat-XXXXXX)"
BASE_TREE="$WORKDIR/baseline"
OUT="$WORKDIR/out"
mkdir -p "$OUT"

cleanup() {
	git worktree remove "$BASE_TREE" --force >/dev/null 2>&1 || true
	rm -rf "$WORKDIR"
}
trap cleanup EXIT

echo "==> baseline ref: $BASELINE_REF ($(git log -1 --format='%h %s' "$BASELINE_REF"))"
echo "==> candidate:    $(git rev-parse --abbrev-ref HEAD) ($(git log -1 --format='%h %s' HEAD))"

echo "==> building baseline in worktree $BASE_TREE"
git worktree add --quiet --detach "$BASE_TREE" "$BASELINE_REF"
# Not silenced: a failure here aborts the whole check (set -e), so the baseline
# install/build output must be visible in CI to diagnose it — see the env line below.
echo "    node $(node --version), npm $(npm --version)"
( cd "$BASE_TREE" && npm ci && npm run build )

echo "==> building current checkout"
npm run build --silent

echo "==> extracting contracts"
node "$REPO_ROOT/docs/backward-compatibility-check/extract-contract.cjs" "$BASE_TREE/dist" > "$OUT/baseline.json"
node "$REPO_ROOT/docs/backward-compatibility-check/extract-contract.cjs" "$REPO_ROOT/dist" > "$OUT/candidate.json"

# Generated report + snapshots go to the gitignored scratch dir — they are
# point-in-time output (true only for this baseline/candidate pair), not source.
SCRATCH="$REPO_ROOT/.local"
mkdir -p "$SCRATCH"
REPORT="$SCRATCH/backward-compatibility-check-findings.md"

echo "==> diffing"
set +e
DIFF_OUT="$(node "$REPO_ROOT/docs/backward-compatibility-check/diff-contract.cjs" "$OUT/baseline.json" "$OUT/candidate.json")"
RC=$?
set -e

echo "$DIFF_OUT"

# Snapshots for inspection.
cp "$OUT/baseline.json" "$SCRATCH/baseline.snapshot.json"
cp "$OUT/candidate.json" "$SCRATCH/candidate.snapshot.json"

# Write a self-describing report capturing exactly what was compared.
BASE_DESC="$(git log -1 --format='%h %s' "$BASELINE_REF")"
CAND_REF="$(git rev-parse --abbrev-ref HEAD)"
CAND_DESC="$(git log -1 --format='%h %s' HEAD)"
{
	echo "# Backward-compatibility check findings"
	echo
	echo "> Generated by \`docs/backward-compatibility-check/run.sh\`. Point-in-time output — regenerate, don't edit."
	echo
	echo "- **Baseline:** \`$BASELINE_REF\` ($BASE_DESC)"
	echo "- **Candidate:** \`$CAND_REF\` ($CAND_DESC)"
	echo "- **Snapshots:** \`.local/{baseline,candidate}.snapshot.json\`"
	echo
	echo '```'
	echo "$DIFF_OUT"
	echo '```'
} > "$REPORT"

echo "==> report saved to .local/backward-compatibility-check-findings.md"
echo "==> snapshots saved to .local/{baseline,candidate}.snapshot.json"

exit $RC
